

CREATE DATABASE SUCOS_VENDAS_001

CREATE DATABASE SUCOS_VENDAS_002
ON (NAME = SUCOS_VENDAS_DAT, FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SUCOS_VENDAS.mdf', SIZE = 10, MAXSIZE = 50, FILEGROWTH = 5)
LOG ON (NAME = SUCOS_VENDAS_LOG, FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SUCOS_VENDAS.ldf', SIZE = 10, MAXSIZE = 50, FILEGROWTH = 5);