
/* ALTERAR A TABELA PARA NÃO ACEITAR VALORES NULL NO CAMPO */
ALTER TABLE [PRODUTOS]
ALTER COLUMN [CODIGO DO PRODUTO]
VARCHAR (10) NOT NULL

ALTER TABLE [VENDEDORES]
ALTER COLUMN [MATRICULA]
VARCHAR (5) NOT NULL

ALTER TABLE [CLIENTES]
ALTER COLUMN [CPF]
VARCHAR (11) NOT NULL

/* APÓS O COMANDO ACIMA É POSSÍVEL ALTERAR A TABELA PARA RECEBER UMA CHAVE PRIMÁRIA */
ALTER TABLE [VENDEDORES]
ADD CONSTRAINT PK_VENDEDORES
PRIMARY KEY CLUSTERED ([MATRICULA])

ALTER TABLE [CLIENTES]
ADD CONSTRAINT PK_CLIENTES
PRIMARY KEY CLUSTERED ([CPF])