
UPDATE [TABELA DE PRODUTOS] SET 
[EMBALAGEM] = 'Lata',
[PREÇO DE LISTA] = 2.46
WHERE [CODIGO DO PRODUTO] = '544931'

UPDATE [TABELA DE PRODUTOS] SET
[EMBALAGEM] = 'Garrafa'
WHERE [CODIGO DO PRODUTO] = '1078680'

UPDATE [VENDEDORES] SET
[PERCENTUAL COMISSAO] = 0.11
WHERE [MATRICULA] = '00238'

UPDATE [VENDEDORES] SET
[NOME] = 'José Geraldo da Fonseca Junior'
WHERE [MATRICULA] = '00233'





