
INSERT INTO [VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00233','José Geraldo da Fonseca', 0.10)

INSERT INTO [VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00235','Márcio Almeida Silva', 0.08)

INSERT INTO [VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00236','Cláudia Morais', 0.08)