
CREATE TABLE [PRODUTOS]
(
[CODIGO DO PRODUTO] [VARCHAR] (10),
[NOME DO PRODUTO] [VARCHAR] (50),
[EMBALAGEM] [VARCHAR] (20),
[TAMANHO] [VARCHAR] (10),
[SABOR] [VARCHAR] (20),
[PRECO DE LISTA] [SMALLMONEY]
)